# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
    build:
      working_directory: ~/server
      docker:
        - image: circleci/node:current
          environment:
          # Mongo connection info in Platform.sh format
        - image: mongo:3.4.24
          command: [--auth]
        - image: mongo:3.4.24
          command: |
            mongo
            quit()
      steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: The First Step
          command: |
            ls -al
            echo 'That should look familiar'
      - run: npm install
      - run: npm install mocha
      - run:  npm install express
      - run:  npm install cors
      - run:  npm install chai
      - run:  npm install chai-http
      - run:  npm install mongoose
      - run:
          name: Installing MongoDB
          command: |
            cd server
            wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
            sudo apt-get purge mongodb-org*
            sudo apt-get purge mongo*
            sudo apt-get update
            echo "Passed apt-get update"
            sudo apt-get install -y mongodb-org
            echo 'Passed: sudo apt-get install -y mongodb-org'
            sudo service mongodb start
          background: true
      - run: 
          name: Start Server
          command: |
            cd server
            npm install lsof
            sudo pkill node
            sudo npm start
          background: true
      - run: 
          name: Run Server Tests
          command: |
            cd server
            npm test