# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
    build:
      working_directory: ~/server
      docker:
        - image: circleci/node:current
          
      steps:
        - checkout:
            path: ~HEAL-Central/server
          
        - run: npm install
        - run: npm install mocha
        - run:
            command: node index.js
            background: true
        - run: mocha