import Home from './Home'
import About from './About'
import Calendar from './Calendar'
import Gallery from './Gallery'
import ExecBoard from './ExecBoard'
import AttendeesInsert from './AttendeesInsert'
import AttendeesList from './AttendeesList'
import AttendeesUpdate from './AttendeesUpdate'
import SignUp from './SignUp'
import Login from './Login'
export { Home, About, Calendar, Gallery, ExecBoard, AttendeesInsert, AttendeesList, AttendeesUpdate, SignUp, Login }